### ISSUE TITLE
Develop small MQTT forwarder

### ISSUE THREAD

**Issue by DavyLandman** [SWAT-engineering/kiwi-air-monitor#5]
subscribe to `kiwi/+/sensor/#` stream, and forward the measurements to influxdb.

Tag based on mac, and have a map of extra tags that can be registered for each mac.

For example toml config:

```toml
[servers]
mqtt = "mqtts://iot:password@mqtt-servername"
influxdb = "http://influxdb"
influxdb_name = "kiwi"

[[client.tags]]
mac = "30:AE:A4:07:0D:64"
tags = [ "1st floor", "front-side"]

[[client.tags]]
mac = "30:AE:A4:07:0D:55"
tags = [ "2st floor", "front-side"]
```
